package by.alexandr7035.affinidi_id.core

enum class ErrorType {
    FAILED_CONNECTION,
    USER_ALREADY_EXISTS,
    USER_DOES_NOT_EXIST,
    WRONG_USERNAME_OR_PASSWORD,
    WRONG_CONFIRMATION_CODE,
    UNKNOWN_ERROR
}